2023-09-05 13:21:12,316 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask_mail.py", line 181, in send
    if message.has_bad_headers():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask_mail.py", line 400, in has_bad_headers
    headers = [self.sender, self.reply_to] + self.recipients
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: can only concatenate list (not "str") to list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\app\routes.py", line 176, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Yash\PycharmProjects\microblog\app\email.py", line 15, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "C:\Users\Yash\PycharmProjects\microblog\app\email.py", line 10, in send_email
    mail.send(msg)
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "C:\Users\Yash\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 1004, in quit
    res = self.docmd("quit")
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "C:\Users\Yash\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "C:\Users\Yash\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2023-09-06 11:56:21,500 INFO: Microblog startup [in C:\Users\Yash\PycharmProjects\microblog\app\__init__.py:30]
